# Enable standard AMQP
listeners.tcp.default = 5672

# Enable TLS AMQP for your PQC pipeline
listeners.ssl.default = 5671

# Link the certificates we mapped from Windows
ssl_options.cacertfile = /etc/rabbitmq/certs/ca_certificate.pem
ssl_options.certfile   = /etc/rabbitmq/certs/server_certificate.pem
ssl_options.keyfile    = /etc/rabbitmq/certs/server_key.pem

# TLS Validation settings
ssl_options.verify = verify_none
ssl_options.fail_if_no_peer_cert = false