version: '3.8'

services:
  besu:
    image: hyperledger/besu:22.7.1
    container_name: besu-node
    user: "0"
    command: [
      "--network=dev",
      "--rpc-http-enabled=true",
      "--rpc-http-host=0.0.0.0",
      "--rpc-http-port=8545",
      "--rpc-http-cors-origins=all",
      "--rpc-http-api=ETH,NET,WEB3,DEBUG,TXPOOL,MINER",
      "--host-allowlist=all",
      "--data-path=/opt/besu/data",
      "--miner-enabled",
      "--miner-coinbase=0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"
    ]
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - besu-data:/opt/besu/data
    restart: unless-stopped

  alethio-explorer:
    image: alethio/ethereum-lite-explorer
    container_name: alethio-explorer
    environment:
      - APP_NODE_URL=http://127.0.0.1:8545
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  besu-data:
